# Generated by Django 5.0.7 on 2024-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_movie_name', models.CharField(default='No name', max_length=100)),
                ('V_duration', models.CharField(max_length=50)),
                ('V_genre', models.CharField(max_length=50)),
                ('V_director', models.CharField(max_length=60)),
                ('V_lead_actor', models.CharField(max_length=100)),
                ('V_language', models.CharField(max_length=100)),
            ],
        ),
    ]
