# Generated by Django 5.0.7 on 2024-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vrishabha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_Movie_Name', models.CharField(default='No name', max_length=100)),
                ('V_trailer', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('V_launch_date', models.DateField()),
            ],
        ),
    ]
